### ISSUE TITLE
Repository Branches

### ISSUE THREAD

**Issue by stuntguy3000** [robvanderleek/JLifx#173]
Hi,

Just confirming, which is the main development branch?

I've got some things to add, but I want to make sure I do it in the right spot.

Cheers

**Comment by robvanderleek** [comment]
Hi @stuntguy3000 

I've switched to `main` a while ago, let me know if you spot things pointing to other branches.
Your other PR has been merged into `main` 🙂 

Thanks for your contributions. This is a bit of a dormant project, let me know if you need help, want a Maven release, etc. I gave you permissions to run the `ci.yml` workflow in a fork.

Kind regards,
Rob

**Comment by stuntguy3000** [comment]
Thanks Rob! I much appreciate it. I'm working with this API more and will make any contributions I see fit.

Cheers
