### ISSUE TITLE
Make PacketService methods static

### ISSUE THREAD

**Issue by CrendKing** [robvanderleek/JLifx#92]
All methods from `io.github.robvanderleek.jlifx.packet.PacketService` can be static, making the class easier to use and save an unnecessary object.

**Comment by robvanderleek** [comment]
It's true that `PacketService` has no internal state but I would like to be able to mock this class with Mockito. 
For most operations `PacketService` should not be used directly, please use the convenience methods in `Bulb`. Let me know if this will not work with your use-case.
